import { symbol } from '../shell';
export function paymentLayout(){return `
<div id="transfer-home" class="transfer-home payment-home">
  <div class="transfer-heading payment-heading"><div><div class="product-eyebrow">VERDICT / PAYMENTS</div><h1 id="transfer-title">新建付款</h1></div><span id="payment-today" class="payment-today"></span></div>
  <nav class="payment-tabs" aria-label="付款工作台"><button data-payment-tab="compose" class="active">新建付款</button><button data-payment-tab="records">付款记录 <span id="payment-record-count">0</span></button></nav>
  <div id="payment-compose">
    <section class="payment-presets"><div class="payment-section-heading"><div><h2>常用付款条件 <span class="local-tag">本机</span></h2></div><button id="preset-add" class="product-quiet" type="button">＋ 保存付款条件</button></div><div id="preset-list" class="preset-list"></div></section>
    <div class="transfer-layout payment-compose-grid">
      <section class="transfer-card"><div class="transfer-card-top"><span>${symbol('arrow')}本次付款</span><span class="transfer-type" id="operation-type">原生币</span></div>
      <form id="wallet-form"><fieldset id="wallet-fields">
        <label class="product-label" for="payment-label">付款对象</label><input id="payment-label" class="address-input" autocomplete="off" maxlength="80" placeholder="名称或付款备注（选填）">
        <div class="operation-switch" id="operation-switch" hidden><label for="wallet-operation">操作类型</label><select id="wallet-operation"><option value="native_transfer">原生币付款</option><option value="erc20_transfer">代币付款</option><option value="erc20_approve">代币授权</option></select></div>
        <label class="product-label">发送账户<button type="button" class="account-field" id="wallet-connect-card"><span class="account-avatar">${symbol('wallet')}</span><span><b id="form-account">连接钱包</b><small id="form-network">选择发送账户</small></span><span class="field-chevron">⌄</span></button></label><div class="form-divider"><span>↓</span></div>
        <div id="token-fields" hidden><label class="product-label" for="wallet-token">代币合约</label><input id="wallet-token" class="address-input" autocomplete="off" spellcheck="false" placeholder="0x…" pattern="0x[0-9a-fA-F]{40}" disabled></div>
        <label class="product-label" id="recipient-label" for="wallet-recipient">收款地址</label><input id="wallet-recipient" class="address-input" autocomplete="off" spellcheck="false" required placeholder="0x…" pattern="0x[0-9a-fA-F]{40}">
        <div class="amount-heading"><label class="product-label" id="amount-label" for="wallet-amount">付款金额</label><span id="wallet-balance">余额 —</span></div><div class="amount-field"><input id="wallet-amount" inputmode="decimal" autocomplete="off" required placeholder="0.00" aria-label="付款金额"><span class="asset-pill"><span class="asset-mark">◈</span><b id="wallet-symbol">—</b></span></div>
        <details class="transfer-settings"><summary>交易设置 <span>⌄</span></summary><label for="wallet-fee">最高网络费用</label><div class="fee-field"><input id="wallet-fee" inputmode="decimal" required placeholder="0.00"><span id="fee-symbol">—</span></div><p id="wallet-limit"></p></details>
        <div id="wallet-form-status" class="form-status" role="status">正在连接审查服务…</div><button type="submit" class="product-primary" id="wallet-submit" disabled><span>核对条件并开始审查</span>${symbol('arrow')}</button>
      </fieldset></form></section>
      <aside class="payment-scope"><div class="payment-section-heading"><h2>本次付款条件</h2><button id="preset-clear" class="product-quiet" type="button" hidden>重设条件</button></div><div id="scope-preview"></div><div class="aside-network"><span>当前网络</span><b id="aside-network">未连接</b></div><div class="aside-parcel">${symbol('parcel')}</div><ol class="process-list"><li><span>01</span><div>确认付款条件<small>收款人 · 金额 · 网络</small></div></li><li><span>02</span><div>检查实际交易<small>差异对照 · 链上预执行</small></div></li><li><span>03</span><div>逐笔确认<small>手写姓名 · 钱包签名</small></div></li><li><span>04</span><div>查看链上结果<small>回执 · 状态 · 证据</small></div></li></ol><button id="wallet-demo-start" type="button" class="product-secondary demo-entry">使用模拟配置体验</button></aside>
    </div>
  </div>
  <section id="payment-records" class="payment-records" hidden><div class="payment-section-heading"><h2>付款记录 <span class="local-tag">本机</span></h2><label class="records-filter">状态<select id="payment-record-filter"><option value="all">全部</option><option value="attention">需要处理</option><option value="waiting">等待链上结果</option><option value="done">已有回执</option></select></label></div><div id="payment-record-list"></div></section>
</div>
<section id="transfer-track" class="transfer-track" hidden>
  <div class="tracking-heading"><div><div class="product-eyebrow">VERDICT / PAYMENT</div><h1 id="tracking-title">付款进度</h1><span id="demo-mode-badge" class="demo-mode-badge" hidden>模拟体验 · UI_MOCK</span></div><div class="tracking-nav"><button id="track-records" class="product-quiet">付款记录</button><button id="transfer-edit" class="product-quiet">修改付款 ↗</button></div></div>
  <div id="payment-milestones"></div>
  <div class="shipment-summary"><div><span class="summary-icon">${symbol('arrow')}</span><div><span id="track-payee-label">本次付款</span><strong id="track-amount"></strong></div></div><div class="shipment-recipient"><span>收款地址</span><code id="track-to"></code></div><div><span>网络</span><strong id="track-network"></strong></div></div>
  <section id="payment-comparison" class="payment-comparison"></section>
  <div class="route-card"><div class="route-card-header"><span class="route-state" id="track-status" role="status"></span><span class="record-source" id="track-source"></span></div><div id="route-map-shell"></div><div class="route-card-footer"><span id="track-reason"></span><code id="track-id"></code></div></div>
  <div class="tracking-columns"><section class="journey-card"><div class="journey-title"><h2>付款行动记录</h2><button id="wallet-refresh" class="product-quiet">刷新 ↻</button></div><p id="graph-error" class="inline-error" hidden></p><div id="confirmation-record" class="confirmation-record" hidden></div><ol id="journey-events" class="journey-events"></ol><details class="checks-detail"><summary>检查结果 <span id="checks-count"></span></summary><div id="wallet-checks"></div></details></section>
  <aside class="decision-card"><div id="decision-result"></div><div id="confirmation-summary"></div><dl id="contract-summary" class="receipt-fields" hidden></dl>
    <section id="signature-section" hidden><div class="signature-title"><label for="signature-canvas">手写姓名</label><button id="signature-clear" type="button" class="product-quiet">清除</button></div><div class="signature-surface"><canvas id="signature-canvas" aria-label="手写姓名签名区" tabindex="0"></canvas><span id="signature-placeholder">在此签写姓名</span><span class="signature-line"></span></div><div class="signature-meta"><span id="signature-status">待签写</span><span id="permit-expiry"></span></div><button id="wallet-sign" class="product-primary" disabled><span>确认本笔并前往钱包</span>${symbol('arrow')}</button></section>
    <div id="track-actions" class="track-actions"></div><div id="receipt-tracking" role="status"></div><div id="observation-summary"></div><div id="wallet-receipt"></div><div id="wallet-evidence"></div>
  </aside></div>
</section><div id="wallet-error" class="product-alert" role="alert" hidden></div>
<dialog id="preset-dialog" class="wallet-dialog preset-dialog"><div class="dialog-heading"><h2>保存付款条件</h2><button id="preset-close" type="button" class="icon-button" aria-label="关闭付款条件">×</button></div><form id="preset-form"><label>付款对象<input id="preset-label" required maxlength="80" autocomplete="off" placeholder="供应商或收款人名称"></label><label>收款地址<input id="preset-recipient" required pattern="0x[0-9a-fA-F]{40}" spellcheck="false" placeholder="0x…"></label><div class="preset-scope-context"><span id="preset-network"></span><span id="preset-account"></span></div><label>付款金额上限<input id="preset-limit" required inputmode="decimal" placeholder="0.00"></label><label>最高网络费用<input id="preset-fee" required inputmode="decimal" placeholder="0.00"></label><p id="preset-error" role="alert" hidden></p><button class="product-primary" type="submit">确认并保存到本机</button></form></dialog>
<dialog id="wallet-dialog" class="wallet-dialog"><div class="dialog-heading"><h2>连接钱包</h2><button id="wallet-dialog-close" class="icon-button" aria-label="关闭钱包选择">×</button></div><div id="wallet-choices"></div><p id="wallet-discovery-empty">未发现浏览器钱包</p><button id="wallet-disconnect" class="product-quiet" hidden>断开连接</button><p id="wallet-connect-error" role="alert" hidden></p></dialog>`;}
